# This is a basic workflow to help you get started with Actions

name: Deployment pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup node.js
      - uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: npm install
        run: npm install        
      - name: lint
        run: npm run eslint
      - name: test
        run: npm test

      - name: build
        run: npm run build

      # run cypress tests ex 11.9
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with: 
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      
      # deploy to heroku
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fso-pokedex-cm" #Must be unique in Heroku
          heroku_email: "webmaster@cherylli.com"
          healthcheck: "https://fso-pokedex-cm.herokuapp.com/health"
          checkstring: "ok"
      
